ci: Use taiki-e/github-actions/free-device-space action in msrv job
```
  error: failed to extract package

  Caused by:
      No space left on device (os error 28)
```